/**
 * Coefficients are derived from Tables 1 and 2 of ITU-R BS.1770-5.
 * Coefficients for other sample rates are generated by bilinear remapping of the specified 48 kHz transfer functions.
 *
 * @param stage The filter stage containing the coefficients to be retargeted.
 * @param reference The reference sample rate of the original filter coefficients.
 * @param target The target sample rate to which the filter coefficients should be retargeted.
 * @returns The retargeted filter coefficients for the target sample rate.
 */
function retarget(
  stage: { a: [number, number]; b: [number, number, number] },
  reference: number,
  target: number,
): { a: [number, number]; b: [number, number, number] } {
  if (reference <= 0 || target <= 0) {
    throw new RangeError("Sample rate must be positive.");
  }

  if (reference === target) {
    return { a: [...stage.a], b: [...stage.b] };
  }

  const r = target / reference;
  const a = 1 - r;
  const b = 1 + r;
  const aa = a * a;
  const bb = b * b;
  const ab = a * b;
  const b0 = stage.b[0] * bb + stage.b[1] * ab + stage.b[2] * aa;
  const b1 = 2 * ab * (stage.b[0] + stage.b[2]) + stage.b[1] * (aa + bb);
  const b2 = stage.b[0] * aa + stage.b[1] * ab + stage.b[2] * bb;
  const a0 = 1 * bb + stage.a[0] * ab + stage.a[1] * aa;
  const a1 = 2 * ab * (1 + stage.a[1]) + stage.a[0] * (aa + bb);
  const a2 = 1 * aa + stage.a[0] * ab + stage.a[1] * bb;

  return {
    b: [b0 / a0, b1 / a0, b2 / a0],
    a: [a1 / a0, a2 / a0],
  };
}

export { retarget };
